baseURL: "https://edwardharvey.com" 
title: L. Edward Harvey
paginate: 20
theme: PaperMod

enableInlineShortcodes: true
enableRobotsTXT: true

taxonomies:
    tag: tags

menu:
    main:
        - name: Search
          url: search/
          weight: 1
        - name: Archive  
          url: /archive/  
          weight: 2



params:
    description: "I am a former IT professional with 23 years experience in data science and web development, and university professor for 10 years in Canada and New Zealand."
    author: L. Edward Harvey
    # googleAnalyticsID: "G-XXXXX"
    DateFormat: "January 2006"
    defaultTheme: dark
    hideFooter: false
    disableThemeToggle: true
    ShowShareButtons: false
    ShowReadingTime: false
    disableSpecial1stPost: true
    disableAnchoredHeadings: true
    ShowPostNavLinks: false
    ShowBreadCrumbs: false
    ShowCodeCopyButtons: true
    ShowRssButtonInSectionTermList: false
    ShowToc: false
    disableScrollToTop: true
    TocOpen: true
    ShowWordCount: false
    UseHugoToc: true
    comments: false
    math: true
    profileMode:
          enabled: true
          title: L. Edward Harvey
          subtitle: "I am a former Information Technology professional with over 23 years experience in data science, and application development and support, and 10 years as an academic scientist in Canadian and New Zealand universities. My IT roles have included development team lead, developer, business analyst, systems analyst, and application and information architect. I have also authored 30 publications on applied multivariate statistics and spatial analysis. Certified, ITIL Foundation."
          imageUrl: "moko399x399.png"
          imageWidth: 160
          imageHeight: 160
          imageTitle: L. Edward Harvey
          buttons:


    socialIcons:
        - name: Email
          url: mailto:ed.harvey@gmail.com
        - name: Resume
          url: https://edwardharvey.com/resume.html
        - name: Google Scholar
          url: https://scholar.google.com/citations?user=MhzVJOgAAAAJ&hl=en
        - name: Orcid
          url: https://orcid.org/0000-0002-2379-4187
        - name: Location
          url: location/
        - name: GitHub
          url: https://github.com/moko
        - name: LinkedIn
          url: https://www.linkedin.com/in/edharvey
        - name: Mastodon
          url: https://mstdn.ca/@moko


    assets:
        disableHLJS: true
        disableScrollBarStyle: true
    cover:
        hiddenInList: false
        hiddenInSingle: true
    label:
      text: "L. Edward Harvey"
      icon: favicon.ico
      iconHeight: 18

markup:
    goldmark:
        renderer:
            unsafe: true
    highlight:
        guessSyntax: true
        style: autumn 
    tableOfContents:
        endLevel: 2
        ordered: false
        startLevel: 2

outputs:
    home:
      - HTML
      - RSS
      - JSON